// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Stock struct {
	ID            int32        `json:"id"`
	UserID        int32        `json:"user_id"`
	StockName     string       `json:"stock_name"`
	Action        string       `json:"action"`
	Quantity      int32        `json:"quantity"`
	Price         string       `json:"price"`
	OriginalValue string       `json:"original_value"`
	Date          sql.NullTime `json:"date"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID          int32          `json:"id"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	Email       string         `json:"email"`
	Phone       sql.NullString `json:"phone"`
	Address     sql.NullString `json:"address"`
	City        sql.NullString `json:"city"`
	Country     sql.NullString `json:"country"`
	OtpCode     sql.NullString `json:"otp_code"`
	OtpExpires  sql.NullTime   `json:"otp_expires"`
	OtpVerified sql.NullBool   `json:"otp_verified"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}
