// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteStock(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetStock(ctx context.Context, id int32) (Stock, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailAndOTP(ctx context.Context, arg GetUserByEmailAndOTPParams) (User, error)
	GetUserOTP(ctx context.Context, id int32) (GetUserOTPRow, error)
	ListStocks(ctx context.Context) ([]Stock, error)
	ListStocksByUser(ctx context.Context, userID int32) ([]Stock, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserOTP(ctx context.Context, arg UpdateUserOTPParams) (User, error)
	VerifyUserOTP(ctx context.Context, arg VerifyUserOTPParams) (User, error)
}

var _ Querier = (*Queries)(nil)
