// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stocks.sql

package db

import (
	"context"
	"database/sql"
)

const createStock = `-- name: CreateStock :one
INSERT INTO stocks (
  user_id, stock_name, action, quantity, price, original_value, date
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, stock_name, action, quantity, price, original_value, date, created_at, updated_at, deleted_at
`

type CreateStockParams struct {
	UserID        int32        `json:"user_id"`
	StockName     string       `json:"stock_name"`
	Action        string       `json:"action"`
	Quantity      int32        `json:"quantity"`
	Price         string       `json:"price"`
	OriginalValue string       `json:"original_value"`
	Date          sql.NullTime `json:"date"`
}

func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, createStock,
		arg.UserID,
		arg.StockName,
		arg.Action,
		arg.Quantity,
		arg.Price,
		arg.OriginalValue,
		arg.Date,
	)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StockName,
		&i.Action,
		&i.Quantity,
		&i.Price,
		&i.OriginalValue,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteStock = `-- name: DeleteStock :exec
DELETE FROM stocks
WHERE id = $1
`

func (q *Queries) DeleteStock(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteStock, id)
	return err
}

const getStock = `-- name: GetStock :one
SELECT id, user_id, stock_name, action, quantity, price, original_value, date, created_at, updated_at, deleted_at FROM stocks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStock(ctx context.Context, id int32) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStock, id)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StockName,
		&i.Action,
		&i.Quantity,
		&i.Price,
		&i.OriginalValue,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listStocks = `-- name: ListStocks :many
SELECT id, user_id, stock_name, action, quantity, price, original_value, date, created_at, updated_at, deleted_at FROM stocks
ORDER BY id
`

func (q *Queries) ListStocks(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listStocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stock{}
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StockName,
			&i.Action,
			&i.Quantity,
			&i.Price,
			&i.OriginalValue,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocksByUser = `-- name: ListStocksByUser :many
SELECT id, user_id, stock_name, action, quantity, price, original_value, date, created_at, updated_at, deleted_at FROM stocks
WHERE user_id = $1
ORDER BY date DESC
`

func (q *Queries) ListStocksByUser(ctx context.Context, userID int32) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listStocksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stock{}
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StockName,
			&i.Action,
			&i.Quantity,
			&i.Price,
			&i.OriginalValue,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStock = `-- name: UpdateStock :one
UPDATE stocks
SET stock_name = $2, action = $3, quantity = $4, price = $5, original_value = $6, date = $7, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, stock_name, action, quantity, price, original_value, date, created_at, updated_at, deleted_at
`

type UpdateStockParams struct {
	ID            int32        `json:"id"`
	StockName     string       `json:"stock_name"`
	Action        string       `json:"action"`
	Quantity      int32        `json:"quantity"`
	Price         string       `json:"price"`
	OriginalValue string       `json:"original_value"`
	Date          sql.NullTime `json:"date"`
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStock,
		arg.ID,
		arg.StockName,
		arg.Action,
		arg.Quantity,
		arg.Price,
		arg.OriginalValue,
		arg.Date,
	)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StockName,
		&i.Action,
		&i.Quantity,
		&i.Price,
		&i.OriginalValue,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
