// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  first_name, last_name, email, phone, address, city, country
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, first_name, last_name, email, phone, address, city, country, otp_code, otp_expires, otp_verified, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Address   sql.NullString `json:"address"`
	City      sql.NullString `json:"city"`
	Country   sql.NullString `json:"country"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.Country,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.OtpCode,
		&i.OtpExpires,
		&i.OtpVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, email, phone, address, city, country, otp_code, otp_expires, otp_verified, created_at, updated_at, deleted_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.OtpCode,
		&i.OtpExpires,
		&i.OtpVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, phone, address, city, country, otp_code, otp_expires, otp_verified, created_at, updated_at, deleted_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.OtpCode,
		&i.OtpExpires,
		&i.OtpVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmailAndOTP = `-- name: GetUserByEmailAndOTP :one
SELECT id, first_name, last_name, email, phone, address, city, country, otp_code, otp_expires, otp_verified, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND otp_code = $2 LIMIT 1
`

type GetUserByEmailAndOTPParams struct {
	Email   string         `json:"email"`
	OtpCode sql.NullString `json:"otp_code"`
}

func (q *Queries) GetUserByEmailAndOTP(ctx context.Context, arg GetUserByEmailAndOTPParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailAndOTP, arg.Email, arg.OtpCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.OtpCode,
		&i.OtpExpires,
		&i.OtpVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserOTP = `-- name: GetUserOTP :one
SELECT id, email, phone, otp_code, otp_expires, otp_verified FROM users
WHERE id = $1 LIMIT 1
`

type GetUserOTPRow struct {
	ID          int32          `json:"id"`
	Email       string         `json:"email"`
	Phone       sql.NullString `json:"phone"`
	OtpCode     sql.NullString `json:"otp_code"`
	OtpExpires  sql.NullTime   `json:"otp_expires"`
	OtpVerified sql.NullBool   `json:"otp_verified"`
}

func (q *Queries) GetUserOTP(ctx context.Context, id int32) (GetUserOTPRow, error) {
	row := q.db.QueryRowContext(ctx, getUserOTP, id)
	var i GetUserOTPRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.OtpCode,
		&i.OtpExpires,
		&i.OtpVerified,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, first_name, last_name, email, phone, address, city, country, otp_code, otp_expires, otp_verified, created_at, updated_at, deleted_at FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.City,
			&i.Country,
			&i.OtpCode,
			&i.OtpExpires,
			&i.OtpVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = $2, last_name = $3, email = $4, phone = $5, address = $6, city = $7, country = $8, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, first_name, last_name, email, phone, address, city, country, otp_code, otp_expires, otp_verified, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID        int32          `json:"id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Address   sql.NullString `json:"address"`
	City      sql.NullString `json:"city"`
	Country   sql.NullString `json:"country"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.Country,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.OtpCode,
		&i.OtpExpires,
		&i.OtpVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserOTP = `-- name: UpdateUserOTP :one
UPDATE users
SET otp_code = $2, otp_expires = $3, otp_verified = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, first_name, last_name, email, phone, address, city, country, otp_code, otp_expires, otp_verified, created_at, updated_at, deleted_at
`

type UpdateUserOTPParams struct {
	ID          int32          `json:"id"`
	OtpCode     sql.NullString `json:"otp_code"`
	OtpExpires  sql.NullTime   `json:"otp_expires"`
	OtpVerified sql.NullBool   `json:"otp_verified"`
}

func (q *Queries) UpdateUserOTP(ctx context.Context, arg UpdateUserOTPParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserOTP,
		arg.ID,
		arg.OtpCode,
		arg.OtpExpires,
		arg.OtpVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.OtpCode,
		&i.OtpExpires,
		&i.OtpVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const verifyUserOTP = `-- name: VerifyUserOTP :one
UPDATE users
SET otp_verified = true, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND otp_code = $2 AND otp_expires > CURRENT_TIMESTAMP
RETURNING id, first_name, last_name, email, phone, address, city, country, otp_code, otp_expires, otp_verified, created_at, updated_at, deleted_at
`

type VerifyUserOTPParams struct {
	ID      int32          `json:"id"`
	OtpCode sql.NullString `json:"otp_code"`
}

func (q *Queries) VerifyUserOTP(ctx context.Context, arg VerifyUserOTPParams) (User, error) {
	row := q.db.QueryRowContext(ctx, verifyUserOTP, arg.ID, arg.OtpCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.OtpCode,
		&i.OtpExpires,
		&i.OtpVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
